name: 🏁 Windows Builds
on:
  workflow_call:


jobs:
  build-windows:
    runs-on: ${{matrix.os}}
    name: Windows Build ${{ matrix.arch }}
    defaults:
      run:
        shell: powershell
    env:
      # CL: /MP
      CMAKE_GENERATOR: ${{matrix.generator}}
      CMAKE_GENERATOR_PLATFORM: ${{matrix.arch}}
    strategy:
      fail-fast: true
      matrix:
        arch: [x64]
        build_type: [Release]
        lib: [shared]
        include:
          - msvc: VS-17-2022
            os: windows-2022
            generator: 'Visual Studio 17 2022'
            marker: vc17
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
          vsversion: '2022'

      - name: Setup MSVC problem matcher
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          arch: ${{ matrix.arch }}
          platform: windows
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 1

      - name: Upload ${{ matrix.arch }}
        uses: ./.github/actions/upload
